# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='subtitle',
            field=models.CharField(default='Easy peasy!', max_length=255),
            preserve_default=False,
        ),
    ]
