# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madplan', '0003_remove_dish_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
